export const portfolioData = [
    {
        id: 1,
        category: "Web Development",
        techStack: "Next, Typescript, Firebase Firestore, Firebase Functions, Vercel",
        url: "https://sporty.guru/",
        title: "Sporty Guru",
        description: "'Sporty Guru' is go-to platform provided to users and trainers to register themselves and held live sessions. It is mainly solving problems of peoples who have busy schedule and are compromising with their fitness. There are different milestones provided to users for which they get rewarded when they achieve them. It is not only a great platform for workout but also provides personalised work, schedule diet plans.",
        images: "/assets/img/sporty.png",
        slug: "sportyguru",
        shortDescription: "Next, Firebase, Typescript",
        thumbnail: "/assets/img/Sporty1.png",
    },
    {
        id: 2,
        category: "Web Development",
        techStack: "Next, Prisma, PostgreSQL, Typescript",
        url: "https://www.linkedlivin.com/",
        title: "Linkedlivin",
        description: "Linkedlivin is members-only home swapping and renting community. Owners list properties for rental purpose and whosoever users are interested they can chat and make final deal. Stripe is used for seamless transactions for users and owners.",
        images: "/assets/img/Linkedlivin.png",
        slug: "linkedlivin",
        shortDescription: "Next, PostgreSQL, Typescript",
        thumbnail: "/assets/img/linkedlivin1.png",
    },
    {
        id: 3,
        category: "Frontend Development",
        techStack: "React, AWS, Tailwind CSS",
        url: "https://www.adda247.com/",
        title: "Adda247",
        description: "Adda247, a leading education platform with a vast user base. It provides quality education to masses by providing online courses for all major exams in more than 10 regional languages in India. I have developed frontend part and implemented shaka player for live classes.",
        images: "/assets/img/Adda.png",
        slug: "adda247",
        shortDescription: "React, AWS, Tailwind CSS",
        thumbnail: "/assets/img/Adda1.png",
    },
    {
        id: 4,
        category: "Web Development",
        techStack: "React, Node, MYSQL, MongoDB, Tailwind CSS",
        url: "https://www.actyv.ai/",
        title: "Actyv",
        description: "Actyv is AI powered SaaS with B2B and BNPL. I have worked on both frontend and backend part for BNPL portal. Various micro services, NSDL/NESL and many other 3rd party services are integerated.",
        images: "/assets/img/actyv.png",
        slug: "actyv",
        shortDescription: "React, Node, MYSQL, MongoDB",
        thumbnail: "/assets/img/actyv1.png",
    },
    {
        id: 5,
        category: "Web Development",
        techStack: "Next, Node, MongoDB",
        url: "https://www.durgamodelschoolludhiana.com/",
        title: "Durga Model School",
        description: "Durga school is affiliated with the Punjab School Education Board (PSEB), Mohali and prepares students for the Board’s All India Secondary School Examination.",
        images: "/assets/img/durga-1.png",
        slug: "durgamodelschool",
        shortDescription: "Next, Node, MongoDB",
        thumbnail: "/assets/img/durga.png",
    },
    {
        id: 6,
        category: "Frontend Development",
        techStack: "React, Node, MYSQL, Tailwind CSS",
        url: "https://www.momnpophub.com/",
        title: "Mom N Pop",
        description: "MomNPop is a US based application which focused on helping small business owners so that they can register themselves and increase there online presence which result in there increase of sales.",
        images: "/assets/img/momnpop.png",
        slug: "momnpop",
        shortDescription: "React, Node, MYSQL, Tailwind CSS",
        thumbnail: "/assets/img/momnpop1.png",
    }
];
